### ISSUE TITLE
GitHub url is a 404

### ISSUE THREAD

**Issue by polardune-dev** [kylpo/vscode-menu-builder#1]
When looking at the Menu Builder extension in VSC or in the Marketplace online, the URL to this GitHub repo results in a 404 not found.

On the marketplace, the link looks like this: https://github.com/github:kylpo/vscode-menu-builder.git
The "github:" bit in the middle is probably the cause.

Other than that, this extension seems to be just what I was looking for (about to try it). :)

**Comment by kylpo** [comment]
Hey! Thanks for mentioning this, @polardune-dev. 

I believe the url is fixed now. I'll be closing this Issue, but please let me know if the problem persists for you.

Hope you find the extension useful. Cheers!
